# Generated by Django 4.2.2 on 2023-06-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employe_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='timein',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='timeout',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date',
            field=models.DateField(),
        ),
    ]
