# Generated by Django 4.2.2 on 2023-06-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employe_timein_employe_timeout_alter_employe_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='timeworked',
            field=models.CharField(default='', max_length=20),
        ),
    ]
