# Generated by Django 4.2.2 on 2023-06-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employe_timeworked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='timein',
            field=models.DateTimeField(choices=[('0000-00-00 00:00:00', 'default')], default='choose one', null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='timeout',
            field=models.DateTimeField(choices=[('0000-00-00 00:00:00', 'default')], default='choose one', null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='timeworked',
            field=models.CharField(choices=[('1', 'default')], default='', max_length=20),
        ),
    ]
