# Generated by Django 4.2.2 on 2023-06-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_employe_timein_alter_employe_timeout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='timein',
            field=models.DateTimeField(choices=[('default', '0000-00-00 00:00:00')], null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='timeout',
            field=models.DateTimeField(choices=[('default', '0000-00-00 00:00:00')], null=True),
        ),
    ]
