# Generated by Django 4.2.2 on 2023-07-20 12:29

from django.db import migrations, models
import users.storage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_employe_timein_alter_employe_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='image',
            field=models.ImageField(default='default.jpg', storage=users.storage.OverwriteStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='employe',
            name='timein',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='timeout',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='timeworked',
            field=models.CharField(max_length=20),
        ),
    ]
